development:
  adapter: postgresql
  encoding: unicode
  database: dilemma_development
  host: localhost
  pool: 5
  username: ericaporter
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: dilemma_test
  host: localhost
  pool: 5
  username: ericaporter
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dilemma_production
  host: localhost
  pool: 5
  username: ericaporter
  password:
cucumber:
  <<: *test